<Project>
  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisMode>Recommended</AnalysisMode>
    <AzunoteRelease Condition="'$(AzunoteRelease)' == ''">false</AzunoteRelease>
    <DefineConstants Condition="'$(AzunoteRelease)' != 'true'">$(DefineConstants);AZUNOTE_DEV</DefineConstants>
  </PropertyGroup>
</Project>
