name = "Prettier"
shortcut = "Alt+Shift+F"
visibility = "whenAvailable"

[launch]
command = "prettier"
args = ["--write", "${file}"]   # or "--write ${file}"
workingDirectory = "${documentDirname}"
output = ["reloadFile", "ignore"]

[when]
extensions = [".js", ".jsx", ".ts", ".tsx", ".json", ".jsonc", ".json5", ".yaml", ".yml", ".md", ".css", ".less", ".scss", ".html", ".htm"]

[env]
NODE_ENV = "development"
