name = "Prettier"
shortcut = "Alt+Shift+F"
visibility = "whenAvailable"

[launch]
command = "prettier"
args = ["--write", "${file}"]   # or "--write ${file}"
workingDirectory = "${documentDirname}"
output = ["reloadFile", "ignore"]
stdout = "ignore"
stderr = "ignore"

[when]
extensions = [".js", ".jsx", ".ts", ".tsx", ".json", ".css", ".scss", ".html"]

[env]
NODE_ENV = "development"
